import Head from 'next/head'
import styled from 'styled-components'

const Main = styled.main`
  height: 100vh;
  width: 100%;
  background: rgba(var(--dark-color), 1);
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  &:before {
    content: "";
    position: absolute;
    top: -100rem;
    left: -100rem;
    width: 200rem;
    height: 200rem;
    border-radius: 50%;
    background: radial-gradient(rgba(var(--light-color), 0.05), transparent, transparent);
  }
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Main>
     </Main>
    </>
  )
}
